#include <iostream>
#include "Graph.h"
#include "reads.h"

using namespace std;

int main() {
    Graph graph = Graph();
    readStations(&graph, "dataset/stations.csv");
    readNetwork(&graph, "dataset/network.csv");
    cout << "Reached the end!";
    return 0;
}









/*Menu prototype
 *  Doesn't require extra input-2.2,2.3,4.2
 *  Requires extra user given input-2.1,2.4,3.1,4.1
 *
 *  From the input ones,
 *  The ones that require 1 station-2.4
 *  The ones that require 2 stations-2.1,3.1,4.1
 * */

/*
 *  1.1-Menu
 *
 *  1.3-Doxygen
 *
 *  2.1-Calculate the maximum number of trains that can simultaneously travel between
    two specific stations.
 *
 *  2.2-Determine, from all pairs of stations, which ones (if more than one) require the
    most amount of trains when taking full advantage of the existing network capacity;
 *
 *  2.3-Top-k municipalities and districts with higher budget;
 *
 *  2.4-Report the maximum number of trains that can simultaneously arrive at a given station,
    taking into consideration the entire railway grid.
 *
 *  3.1-Calculate the maximum amount of trains that can simultaneously travel between
    two specific stations with minimum cost for the company. Note that your system should also take any
    valid source and destination stations as input;
 *
 *  4.1-Calculate the maximum number of trains that can simultaneously travel between
    two specific stations in a network of reduced connectivity. Reduced connectivity is understood as being
    a subgraph (generated by your system) of the original railway network. Note that your system should
    also take any valid source and destination stations as input;                                                  //perguntar ao stor criterio de reduçao de conectividade(aka, se é só uma linha ou municipalidade)
 *
 *  4.2-Provide a report on the stations that are the most affected by each segment failure,
    i.e., the top-k most affected stations for each segment to be considered.                                      //perguntar ao stor criterio de afetação
 *
 *  5.1-Use the (hopefully) user-friendly interface you have developed to illustrate the
    various algorithm results for a sample set of railway grids which you should develop specifically for the
    purposes of this demo. For instance, you can develop a small set of very modest railway networks for
    contrived capacities so that you can highlight the “correctness” of your solution. For instance, a grid
    that has a “constricted” segment where all traffic must go through, will clearly have a segment very
    “sensitive” to failures.
 * */